### ISSUE TITLE
Error when cacheExtent set to null

### ISSUE THREAD

**Issue by AlexV525** [fluttercandies/extended_tabs#7]
By set `cacheExtent` to null, the error occurred when swiping between tab.
```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following NoSuchMethodError was thrown during performLayout():
The method '_greaterThanFromInteger' was called on null.
Receiver: null
Tried calling: _greaterThanFromInteger(2)

User-created ancestor of the error-causing widget was: 
  ExtendedTabBarView file:///Users/alex/Documents/OpenJMU/lib/pages/home/AppsPage.dart:203:20
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      int.> (dart:core-patch/integers.dart:101:18)
#2      RenderSliverFixedExtentBoxAdaptor._calculateTrailingGarbage (package:flutter/src/rendering/sliver_fixed_extent_list.dart:158:45)
#3      RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:189:35)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
```

**Comment by zmtzawqlp** [comment]
cacheExtent can't be null now
